repos:
-  repo: local
   hooks:
   - id: isort
     name: isort
     entry: poetry run isort
     language: system
     types: [python]

   - id: black
     name: black
     entry: poetry run black
     language: system
     types: [python]

   - id: pylint
     name: pylint
     entry: poetry run pylint
     language: system
     types: [python]
